candlepin/candlepin.github.io

Gemfile
Gemfile.lock
config.ru

Requests to "/foo/bar" are now redirected to "/foo/bar/".  The
redirection is based on a regex that detects if the last portion of the
path contains a period or ends in a slash.  In either of those two
cases, no redirection occurs.

Serve ".md" files; rewrite requests to directories lacking a slash

---

docs/candlepin/per_org_products.md

- Added note to use the org-specific product cert retrieval API call
in place of the org-agnostic one
- Updated the format of the URL placeholders to be consistent
- Added formatting to the example requests for clarity

Updated per-org products migration documentation

---

Gemfile.lock
_data/toc.yaml
docs/candlepin/cp2_migration.md

- Updated the affected and new database table names to reflect the
new names and additional changes
- Updated the list of expected CMV warnings and their explanations
- Renamed the cp2 per-org products document to cp2 migration

Updated the documentation associated with the CP2 migration details

---

.openshift/action_hooks/pre_build

There's a regression in 1.12.1 that causes an error in OpenShift
deployments: Bundler tries to write to a .bundle directory underneath
the home directory which is read-only in OpenShift.

Pin bundler to a working version.

---

config.ru

I've seen several cases where rack-jekyll gets wedged into thinking that
Jekyll is performing the rendering step when it's actually not doing
anything.  This change will just have rack-jekyll always render the site
on start up so there shouldn't be any more false positives about whether
the site is rendering or not.

Force site regeneration every time Rack starts.

---

docs/candlepin/bugzilla_process.md

IMO it is less context switching and less chance for something to fall through the cracks if the reviewer is the one to change the state of any linked bugzilla bug to a PR once they have merged a PR to master.

Reviewer should change the state of the bugzilla during review.

---

docs/candlepin/manifest_extensions.md

Updated the manifest export docs to reflect that
the sync export API supports the 'ext' query
params

Upated manifest export docs

---

docs/candlepin/bugzilla_process.md
docs/subscription-manager/bugzilla_process.md

Update the BZ process so that from an development engineer perspective there is no difference in the new/assigned/post/modified states between candlepin & sub-man other than the flags.

Change sub-man BZ process to be more aligned with candlepin

---

docs/candlepin/schema_updates.md

Made liquibase parameter paths consistent to each other and
added the missing 'target/classes' location for the --classpath.

Fix liquibase parameter paths

---

_includes/footer.html
assets/candlepin.scss

Change the CSS on the footer so that the OpenShift logo stacks correctly
on smaller screen sizes.

Make OpenShift logo responsive.

---

Gemfile.lock

Our site is completely static and nokogiri is only used in the build
process.  But updating the version removes a warning that GitHub shows
and is the right thing to do anyway.

Update Nokogiri to resolve CVE-2017-9050

---

docs/candlepin/amqp.md

- Add information about our own qpid client tool.
- Add a useful list of qpid commands.
- Fix dead links to python/java drain example tools.

Update qpid event monitor/drain instructions

---

docs/candlepin/connect_to_embedded_artemis.md

- Added info on how the client can connect to SSL-enabled artemis.
- Added info on 2-way SSL authentication.

Update information on Artemis SSL config

---

.gitignore
.s2i/bin/assemble
Dockerfile
Gemfile.lock
README.md

Docker doesn't really work on Fedora anymore and isn't provided with
RHEL 8.  The instructions now use podman.  Unfortunately s2i doesn't
work natively with podman, so we have to build an intermediate
Dockerfile now instead of letting s2i build the final container.
Also added some new dependencies like an updated version of Bundler and
python3 which pygments requires.

Update with new instructions for building site container

---

docs/candlepin/developer_deployment.md

- Updated developer_deployment.md to drop references to obsoleted
or removed steps, and updated instructions to use the current
build system and dependencies
- Added a section describing setting up the Vagrant development box
- Added a section describing running unit and spec tests

Modernized the information on the developer deployment

---

docs/candlepin/developer_deployment.md

- Updated the Vagrant install steps for Fedora 35 Workstation installs

Updated Vagrant install and setup instructions for Fedora 35

---

Dockerfile
Gemfile
Gemfile.lock

We haven't actually used Nokogiri for ages.  A long time ago, we used it
for a custom Jekyll plugin that rendered the JSON definition of our API.
That plugin was removed a long time ago, but this dependency wasn't.
The container image for Centos' Ruby 2.7 container had a name change.

Remove Nokogiri. Update container image name

---

.s2i/bin/assemble
README.md

I was seeing the following warnings in the build logs:
[DEPRECATED] The `--deployment` flag is deprecated because it relies on
being remembered across bundler invocations, which bundler will no
longer do in future versions. Instead please use `bundle config set
--local deployment 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being
remembered across bundler invocations, which bundler will no longer do
in future versions. Instead please use `bundle config set --local path
'./bundle'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on
being remembered across bundler invocations, which bundler will no
longer do in future versions. Instead please use `bundle config set
--local without …

Update s2i assemble script to remove deprecated Bundler flags

---

.github/workflows/jekyll.yml

They changed the permissions on the s2i scripts and they're no longer
marked as executable.  Invoke them via bash now.  This has the nice
property of being backwards compatible.

The s2i assemble script is 644 instead of 755 in newer versions

---

_data/toc.yaml
docs/candlepin/inactive_consumer_cleanup_job.md
docs/candlepin/jobs.md

Adding documentation for the newly created inactive consumer cleanup job. I figured it would be a good idea to have some documentation for the new job to bring some clarity on using it, and I wanted to describe the functionality, deletion criteria, and configurable properties of the job.
PR for the newly created job:  https://github.com/candlepin/candlepin/pull/3346

[M] Added documentation for the Inactive Consumer Cleanup Job

---

_data/toc.yaml
docs/candlepin/developers.md
docs/candlepin/mode_agnostic_spec_testing.md

- Updated the developer guidelines for writing commit messages and PR submissions
- Temporarily removed the agnostic spec testing guidelines as they are *very* out of date, and no longer align with neither the current framework, nor spec test standards

ENT-5445: Updated guidelines for commit and PR messaging, and spec testing

---

.github/workflows/deploy.yml
.github/workflows/pr_verification.yml

- When installing the bundler gem the following error was being thrown: "The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22."

Fix bundler gem install error
