candlepin/candlepin.github.io

- docs/candlepin/cmv.md
- docs/candlepin/per_org_products.md
- Added documentation for the cmv tool
- Updated the CP2.0/per-org migration/update page
> Added cmv documentation

- docs/gutterball/reportapi.md
- Updated the JSON output for the consumer status and status
trend reports to reflect recent changes made to the API
> Updated the report api docs

- docs/subscription-manager/installation.md
This documents how to install subscription-manager on Centos 7.
> Adds doc describing how to install subman on Centos 7

- docs/candlepin/event_model.md
Documentation for new HornetQ paging and throttling feature.
Feature PR https://github.com/candlepin/candlepin/pull/1010
> Documentation for HornetQ throttling and paging

- _includes/mastertoc.html
- _layouts/default.html
- _layouts/docs_index.html
- _plugins/docs_index.rb
- assets/candlepin.scss
- docs/candlepin/administration_guide.md
- docs/candlepin/debugging.md
- docs/candlepin/debugging_with_wireshark.md
- docs/candlepin/design.md
- docs/candlepin/developers.md
- docs/candlepin/development.md
- docs/candlepin/general_use_cases.md
- docs/candlepin/getting_started.md
- docs/candlepin/hosted_deployment.md
- docs/candlepin/index.md
- docs/candlepin/old_layout.md
- docs/candlepin/reference.md
- docs/candlepin/standalone_deployment.md
- docs/candlepin/usage.md
- docs/candlepin/user_guide.md
@awood  we talked about this - would you like to review please?
> Adding Jekyll plugin that generates Hierarchical Master Table of Content

- docs/candlepin/swaggerapi.md
Documentation of a new config option to enable/disable swagger.
> Swagger configuration

- docs/candlepin/hibernate.md
Gotcha related to Hibernate locking on MySql
> Hibernate Locking

- _data/toc.yaml
- docs/candlepin/bugzilla_process.md
- docs/candlepin/cleanup_db_backup.md
- docs/candlepin/packaging.md
- docs/subscription-manager/bugzilla_process.md
1. remove suggestion that PR commits on BZs should be private
2. make bz process more visible
3. add useful query to clean up old db backups
> misc. changes

- docs/candlepin/setup.md
Hi,
When I tried to do setup of candlepin at freshly installed CentOS I noticed some missing steps.
Cheers,
Jiri
> Added some other steps to setup.md

- docs/candlepin/amqp.md
Do not merge until candlepin/candlepin#1505 is merged.
> Update AMQP documentation

- docs/subscription-manager/installation.md
Please check style and grammar, because my English could be better.
May be, this documentation could be placed in separate file.
> 1284083: Added notes about installing subman upstream from source code.

- docs/candlepin/running_on_mysql.md
- Added some notes and instructions for setting the default
character collation and transaction isolation level for MySQL/
MariaDB.
> Updated MySQL docs with notes regarding isolation and collation

- docs/subscription-manager/dbus_objects.md
* Added several examples of commands using new D-Bus API
* Changed formatting of main sections to improve orientation
in markdown text.
> Several D-Bus examples

- docs/candlepin/bugzilla_process.md
- docs/subscription-manager/bugzilla_process.md
See http://projects.theforeman.org/projects/foreman/wiki/Security_process
> Add security process based on Foreman's

- docs/subscription-manager/dbus_objects.md
New Consumer object was implemented in this PR: https://github.com/candlepin/subscription-manager/pull/1843
> Added desription of new Consumer object.

- docs/subscription-manager/dbus_objects.md
- added bus information, methods, and examples to
https://www.candlepinproject.org/docs/subscription-manager/dbus_objects.html
for both objects
> ENT-769: Document Entitlement/Syspurpose DBus Objects

- docs/candlepin/autoattach.md
- Changed all appropriate textual sections of how SLA affects autoattach
- Added 'before' & 'after' decision diagrams of pool prioritization & selection based on SLA
- Changed the order of the 'Remove extra attributes' & 'Prune Pools' parts of the algorithm
description since the previous order was out of date.
> Documented new SLA behaviour during Autoattach

- docs/subscription-manager/dbus_objects.md
* Added more examples
* Added list of available options
> Extended documentation about D-Bus API related to entitlements

- docs/subscription-manager/dbus_objects.md
> Added documentation about other signals in D-Bus API.

- docs/candlepin/autoattach.md
- Changed "Pool filtering by SLA" diagram by removing the
SLA override and Owner default SLA since they are no longer used.
- Updated the "Select Best Pools" diagram by removing/adding and
altering the flow order as it currently reflects the code.
- Updated the "Prune Pools" section.
- Updated the "Select Best Entitlement Groups" section.
- Moved the "Pool Priority Algorithm" from a footnote to its own
subsection, which outlines the scoring algorithm in detail,
along with an example of a calculation.
- Minor alterations in other diagrams & descriptions that mention
role & addons in addition to products when it comes to "coverage".
> Update Autoattach page regarding syspurpose; ENT-1220

- docs/candlepin/checkstyle.md
- docs/candlepin/developers.md
Also clean up some of the old references to eclipse
> 1st pass clean up developer instructions to reference gradle 

- docs/candlepin/autoattach.md
Updated diagram and documentation regarding the use of SLAs in Auto attach.
> ENT-2354: Updated documentation & diagram for mix SLAs

- docs/subscription-manager/dbus_objects.md
* Added documentation for two D-Bus methods that are related
to syspurpose
* Improved a little existing documentation of syspurpose methods
* Improved little bit documentation of Facts (added example)
> Extended documentation of syspurpose D-Bus methods

- docs/candlepin/autoattach.md
- Auto attach considers this syspurpose attribute to 
get the best pool depending on the pool priority.
- Updated algorithm to get the pool priority.
> Impact of newly added system purpose attribute: service type [ENT-2798]

- docs/subscription-manager/debug_http_traffic.md
- Reword some sentences
- Add SUBMAN_DEBUG_TCP_IP
- Replace shell scripts with bash-completed function
> Update sub-man's debugging page

- _data/toc.yaml
- docs/candlepin/active_entitlement_job.md
- docs/candlepin/certificate_cleanup_job.md
- docs/candlepin/import_record_cleaner_job.md
- docs/candlepin/job_cleaner_job.md
- docs/candlepin/manifest_cleaner_job.md
- docs/candlepin/orphan_cleanup_job.md
- docs/candlepin/unmapped_guest_entitlement_cleaner_job.md
Added documentation for the following reoccurring jobs:
- Active Entitlement Job
- Certificate Cleanup Job
- Import Record Cleaner Job
- Job Cleaner Job
- Manifest Cleaner Job
- Orphan Cleanup Job
Please let me know if there are any missing important information for the jobs.
> CANDLEPIN-508: Added reoccurring job documentation
